### ISSUE TITLE
Devices id's are switched

### ISSUE THREAD

**Issue by musab1234** [studiosi/OpenCVDeviceEnumerator#3]
![image](https://user-images.githubusercontent.com/8913078/72243367-96c21d00-360d-11ea-9c6e-b9d428e07717.png)

Program listing 'A4 TECH HD PC Camera' as id 1 but when i open VideoCapture from opencv on id 1 it opens defualt laptop camera, and if i put 0 it'll open that usb camera 'A4 TECH HD PC Camera'.

**Comment by studiosi** [comment]
I will take a look into this and get back to this thread. Thanks for reporting.

**Comment by studiosi** [comment]
I have not been able to replicate this, closing unless more information is provided.
